# Generated by Django 5.0 on 2025-03-08 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("reason", models.TextField()),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("source_ip", models.GenericIPAddressField()),
                ("destination_ip", models.GenericIPAddressField()),
                ("source_port", models.IntegerField(blank=True, null=True)),
                ("destination_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(max_length=10)),
                ("packet_info", models.JSONField(default=dict)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("connection", "Connection"),
                            ("port_scan", "Port Scan"),
                            ("ddos", "DDoS Attack"),
                            ("brute_force", "Brute Force Attempt"),
                            ("suspicious_packet", "Suspicious Packet"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("is_threat", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="network_monitor.networkevent",
                    ),
                ),
            ],
        ),
    ]
