# Generated by Django 4.2.20 on 2025-03-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="score_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
